config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root 'lists#index'
  get 'home/trash_em'
  get 'home/trash_em_all'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def trash_em
        @trash_em=List.where(:completed => true).destroy_all
        redirect_to lists_url, notice: "All marked items were successfully deleted." 
    end

    def trash_em_all
        @trash_em_all=List.all.destroy_all
        redirect_to lists_url, notice: "All items were successfully deleted." 
    end



end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @list = List.new
    @lists = List.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_url, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_url, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
  <%= render 'lists/navbar' %>
  <div class="container">
    <br><br>
    <%= render 'flash' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/lists/_flash.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissible">
    <%# <button class="closer" data-dismiss="alert">
        <i class="glyphicon glyphicon-remove-circle"></i>
    </button> %>
    <%= content_tag( :div, msg) %>
    </div>

<% end %>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :description, class:"form-control" %>
  </div>

  <div class="form-group form-check">
    <%= form.check_box :completed, class:"form-check-input" %>
    <%= form.label :completed, style: "display: block", class:"form-check-label" %>

  </div>

  <div class="">
    <%= form.submit "Update", class:"btn btn-outline-success"%>
  </div>
<% end %>

app/views/lists/_form_index.html.erb
<%= form_with(model: list, class: 'form') do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inline my-2 my-lg-0">
    <%= form.text_field :description, class: 'form-control mr-sm-2' %>
    <%= form.submit "Add a To Do", class: 'btn btn-outline-success my-2 my-sm-0' %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
  <p>
    <strong>To Do:</strong>
    <%= list.description %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= list.completed %>
  </p>

</div>

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Todo List", root_path, class:"navbar-brand" %>
 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>

    <%= render partial: 'lists/form_index', locals: { list: @list } %>
  </div>
</nav>

app/views/lists/edit.html.erb
<h1>Edit To Do Item</h1>
<br>
<%= render "form", list: @list %>
<br>
<div>
  <%= link_to "Back", lists_path %>
</div>

app/views/lists/index.html.erb
<table class="table table-bordered my-5">

  <tbody>
  <%# database call %>
    <% @lists.each do |list| %>  
<%# change color of entire row if completed is true:%>
      <% if list.completed %>
        <tr class="bg-secondary text-light">
          <td class="striker"> <%= link_to list.description, edit_list_path(list), class:"text-reset" %> <% list.description %></td>
          <td>
            <%= form_with(model: list) do |form| %>
                <%= form.text_field :description, type: 'hidden'%>
                <%= form.check_box :completed, :checked => false, :style => 'visibility: hidden' %>
                <%= form.submit "Uncheck", class: 'btn btn-sm btn-outline-light'%>
              <% end %>
          </td>
          <td>
            <% link_to "Show", list %>
            <% link_to "Edit", edit_list_path(list) %>
            <center><%= link_to "Delete", list, method: :delete, data: { confirm: "Are you sure you want to delete this list?" }, class:"btn btn-sm btn-outline-danger" %></center>
          </td>
        </tr>

      <% else %>
      <tr>
              <td><%= link_to list.description, edit_list_path(list), class:"text-reset" %><% list.description %></td>
              <td>
              <%= form_with(model: list) do |form| %>
                <%= form.text_field :description, type: 'hidden'%>
                <%= form.check_box :completed, :checked => true, :style => 'visibility: hidden' %>
                <%= form.submit "Check", class: 'btn btn-sm btn-outline-secondary'%>
              <% end %>
              </td>




              <td>
                <% link_to "Show", list %>
                <% link_to "Edit", edit_list_path(list) %>
                <center><%= link_to "Delete", list, method: :delete, data: { confirm: "Are you sure you want to delete this list?" }, class:"btn btn-sm btn-outline-danger" %></center>
              </td>
        </tr>
        <% end %>

    <% end %>
  </tbody>
</table>

<br><br> 
<%= link_to 'Delete Marked Items', home_trash_em_path, data: { confirm: "Are you sure?" }, class: 'btn btn-outline-secondary'%> 
<%= link_to 'Delete All Items', home_trash_em_all_path,data: { confirm: "Are you sure?" }, class: 'btn btn-outline-danger'  %>

<%# turn that ^ intoa form (see other forms) %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<%= render @list %>

<div>
  <%= link_to "Edit this list", edit_list_path(@list) %> |
  <%= link_to "Back to lists", lists_path %>

  <%= button_to "Destroy this list", @list, method: :delete %>
</div>